# PyWebTransport Documentation Issue GitHub Issue Form

name: "📚 Documentation Issue"
description: "Report an issue or suggest an improvement for the documentation."
title: "[Docs]: A brief description of the documentation issue"
labels: ["documentation"]
body:
  - type: input
    id: url
    attributes:
      label: "Affected URL"
      description: "Please provide the URL of the documentation page that has an issue."
      placeholder: "e.g., https://pywebtransport.readthedocs.io/en/latest/api-reference/session.html"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Description of the Issue"
      description: "A clear and concise description of what is wrong, unclear, or missing in the documentation."
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: "Suggested Improvement"
      description: "How could we improve the documentation? If you can, please provide the corrected or new text."
